name: Build and publish

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-publish:
        name: Build and publish
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.x"
        - name: Install pypa/build
          run: >- 
            python3 -m pip install --upgrade pip build wheel --user
        - name: Build
          run: >-
            python3 -m build --sdist --wheel --outdir dist/ .
        - name: Read version
          id: read_version
          run: >-
            echo ::set-output name=VERSION::$(ls dist/*.whl | sed -E 's/.*-([0-9]+\.[0-9]+\.[0-9]+(-[a-z]+)?(-[0-9]+)?).*/\1/')
        - name: Release
          uses: softprops/action-gh-release@v1
          with:
            files: dist/*
            tag_name: ${{ steps.read_version.outputs.VERSION }}
            body: ${{ steps.read_version.outputs.VERSION }}
        - name: Publish
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}