name: Build and publish

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-publish:
        name: Build and publish
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.x"
        - name: Install pypa/build
          run: >- 
            python3 -m pip install --upgrade pip build wheel --user
        - name: Build
          run: >-
            python3 -m build --sdist --wheel --outdir dist/ .
        - name: Release
          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
          uses: softprops/action-gh-release@v1
          with:
            files: dist/*
        - name: Publish
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.PYPI_API_TOKEN }}